# Generated by Django 5.2.7 on 2025-11-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('envio_gratuito_desde', models.DecimalField(decimal_places=2, default=50.0, help_text='Importe mínimo para envío gratuito', max_digits=10)),
                ('coste_envio_estandar', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Datos de Empresa',
                'verbose_name_plural': 'Datos de Empresa',
            },
        ),
    ]
