# Generated by Django 5.2.8 on 2025-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono_clase',
            field=models.CharField(default='bi-grid-3x3-gap', help_text='Clase CSS del icono de Bootstrap', max_length=50),
        ),
    ]
