# Generated by Django 5.2.8 on 2025-11-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_categoria_icono_clase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="icono_clase",
            field=models.CharField(
                default="bi-grid-3x3-gap",
                help_text="Clase CSS del icono de Bootstrap (Ej: bi-bone)",
                max_length=50,
            ),
        ),
    ]
